package com.myspace.pf_rene_svc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String url;

	public PaymentModel() {
	}

	public java.lang.String getUrl() {
		return this.url;
	}

	public void setUrl(java.lang.String url) {
		this.url = url;
	}

	public PaymentModel(java.lang.String url) {
		this.url = url;
	}

}