package com.myspace.pf_rene_svc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PaymentModel() {
    }




}