package com.myspace.pf_rene_svc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Receipt implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String url;

	private java.lang.String channel;

	public Receipt() {
	}

	public java.lang.String getUrl() {
		return this.url;
	}

	public void setUrl(java.lang.String url) {
		this.url = url;
	}

	public java.lang.String getChannel() {
		return this.channel;
	}

	public void setChannel(java.lang.String channel) {
		this.channel = channel;
	}

	public Receipt(java.lang.String url, java.lang.String channel) {
		this.url = url;
		this.channel = channel;
	}

}